#!/bin/bash -e

DIR=$1
[ -n "$DIR" ] && pushd $DIR > /dev/null

while [ "$(/bin/ls -1 hash.* | wc -l)" -gt 1 ]; do
  printf "%s %s\n" $(/bin/ls -1 hash.*) \
    | xargs -P 4 -L 1 ~/projects/glacier-util/tree-hash-combine
done

[ -n "$DIR" ] && popd > /dev/null

