#!/bin/bash -e

filename=$1
BINARY=""

if [ "$1" = "-b" -o "$2" = "-b" ]; then
  if [ "$1" = "-b" ]; then
    filename=$2
  fi
  BINARY="true"
fi

FILE="$(cd "$(dirname "$filename")" && pwd)/$(basename "$filename")"
ONE_MB=1048576
FILE_SIZE=$(stat $FILE | cut -d ' ' -f 1)
TMP_DIR=$(mktemp -d)

pushd $TMP_DIR > /dev/null
  # split the input file into 1mb chunks
  split -b $ONE_MB $FILE part.
  /bin/ls | xargs -L 1 -I{} bash -c 'openssl dgst -sha256 -binary {} > hash.{}'
  rm part.*

  tree-hash-reduce .

  finalhash=$(/bin/ls -1 | head -n 1)
  if [ -z "$BINARY" ]; then
    xxd -ps -c 100 $finalhash
  else
    cat $finalhash
  fi
popd > /dev/null

rm -rf $TMP_DIR
